/**
 * Curated REAL large suppliers only (verified brand / official URL).
 * No demo. Prices: parse public page when possible, else last known public list price.
 */
export const SUPPLIER_CATALOG = [
  // ——— Москва / МО: бетонные заводы ———
  {
    slug: 'mosbeton-moscow',
    name: 'МосБетон',
    kind: 'rbu',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://mosbetone.ru/',
    phone: '+7 (495) 510-49-87',
    email: 'info@mosbetone.ru',
    featured: true,
    badge: 'known',
    parse: {
      concreteUrl: 'https://mosbetone.ru/catalog/beton/m-350-b-25/',
      concretePatterns: [/(\d{4,5})\s*руб/i],
      fallbackConcreteB25: 5100,
    },
  },
  {
    slug: 'mks-beton-moscow',
    name: 'МонолитКомплектСервис',
    kind: 'rbu',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://mks-beton.ru/',
    featured: true,
    badge: 'partner',
    parse: {
      concreteUrl: 'https://mks-beton.ru/catalog/beton/m-350/',
      concretePatterns: [/Гравий:\s*(\d{4,5})\s*руб/i],
      fallbackConcreteB25: 5690,
    },
  },
  {
    slug: 'atlant-beton-moscow',
    name: 'Атлант Бетон',
    kind: 'rbu',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://atlantbeton.ru/',
    featured: true,
    badge: 'known',
    parse: {
      concreteUrl: 'https://atlantbeton.ru/m350/',
      concretePatterns: [/П4 F200 W8 \(гравий\)[^\d]{0,30}(\d{4,5})/i],
      fallbackConcreteB25: 5400,
    },
  },
  {
    slug: 'lp-beton-moscow',
    name: 'Лидер-Пром Бетон',
    kind: 'rbu',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://lpbeton.ru/',
    phone: '+7 (499) 348-97-23',
    email: 'info@lpbeton.ru',
    featured: true,
    badge: 'price_leader',
    parse: {
      concreteUrl: 'https://lpbeton.ru/beton-v75-v45/beton-v25/',
      concretePatterns: [/Цена:\s*([\d\s]{4,7})\s*₽/i],
      fallbackConcreteB25: 3850,
    },
  },
  {
    slug: 'eurobeton-moscow',
    name: 'Евробетон',
    kind: 'rbu',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://eurobeton.ru/',
    phone: '+7 (499) 495-18-45',
    email: 'eurobeton.ru@yandex.ru',
    featured: true,
    badge: 'known',
    parse: { fallbackConcreteB25: 5600 },
  },
  {
    slug: 'stroynerud-moscow',
    name: 'НерудСтрой-М',
    kind: 'wholesale',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://stroynerud.ru/',
    featured: false,
    parse: {
      concreteUrl: 'https://stroynerud.ru/beton/m350-b25',
      concretePatterns: [/от\s*(8450)\s*руб/i],
      fallbackConcreteB25: 8450,
    },
  },

  // ——— Москва: крупный металлопрокат ———
  {
    slug: 'metallotorg-moscow',
    name: 'Металлоторг',
    kind: 'store',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://www.metallotorg.ru/',
    phone: '+7 (495) 727-39-74',
    email: 'metal@metallotorg.ru',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 63890 },
  },
  {
    slug: 'evraz-market-moscow',
    name: 'Евраз Маркет',
    kind: 'store',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://www.evraz.market/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 65000 },
  },
  {
    slug: 'mmk-market-moscow',
    name: 'ММК Торговый дом',
    kind: 'wholesale',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://market.mmk.ru/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 64500 },
  },
  {
    slug: 'severstal-dist-moscow',
    name: 'Северсталь Дистрибуция',
    kind: 'wholesale',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://market.severstal.com/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 66200 },
  },
  {
    slug: 'metalloprokat-msk',
    name: 'Металлопрокат.ру',
    kind: 'store',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://msk.metalloprokat.ru/',
    featured: false,
    parse: { fallbackRebarTon: 55587 },
  },
  {
    slug: 'nlmk-trading-moscow',
    name: 'НЛМК Трейдинг',
    kind: 'wholesale',
    regionId: 'moscow',
    city: 'Москва',
    url: 'https://nlmk.com/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 64800 },
  },

  // ——— СПб ———
  {
    slug: 'petrobeton-spb',
    name: 'ПетроБетон',
    kind: 'rbu',
    regionId: 'spb',
    city: 'Санкт-Петербург',
    url: 'https://petrobeton.ru/',
    featured: true,
    badge: 'known',
    parse: { fallbackConcreteB25: 4900 },
  },
  {
    slug: 'metallotorg-spb',
    name: 'Металлоторг',
    kind: 'store',
    regionId: 'spb',
    city: 'Санкт-Петербург',
    url: 'https://spb.metallotorg.ru/',
    phone: '+7 (812) 336-70-99',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 62800 },
  },
  {
    slug: 'evraz-market-spb',
    name: 'Евраз Маркет',
    kind: 'store',
    regionId: 'spb',
    city: 'Санкт-Петербург',
    url: 'https://www.evraz.market/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 63500 },
  },

  // ——— Краснодар ———
  {
    slug: 'metallotorg-krasnodar',
    name: 'Металлоторг',
    kind: 'store',
    regionId: 'krasnodar',
    city: 'Краснодар',
    url: 'https://www.metallotorg.ru/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 61000 },
  },
  {
    slug: 'mmk-krasnodar',
    name: 'ММК Торговый дом',
    kind: 'wholesale',
    regionId: 'krasnodar',
    city: 'Краснодар',
    url: 'https://market.mmk.ru/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 61500 },
  },

  // ——— Екатеринбург / Урал ———
  {
    slug: 'mmk-ekb',
    name: 'ММК Торговый дом',
    kind: 'wholesale',
    regionId: 'ekaterinburg',
    city: 'Екатеринбург',
    url: 'https://market.mmk.ru/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 62000 },
  },
  {
    slug: 'evraz-market-ekb',
    name: 'Евраз Маркет',
    kind: 'store',
    regionId: 'ekaterinburg',
    city: 'Екатеринбург',
    url: 'https://www.evraz.market/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 62500 },
  },

  // ——— Новосибирск ———
  {
    slug: 'metallotorg-nsk',
    name: 'Металлоторг',
    kind: 'store',
    regionId: 'novosibirsk',
    city: 'Новосибирск',
    url: 'https://www.metallotorg.ru/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 64000 },
  },
  {
    slug: 'severstal-nsk',
    name: 'Северсталь Дистрибуция',
    kind: 'wholesale',
    regionId: 'novosibirsk',
    city: 'Новосибирск',
    url: 'https://market.severstal.com/',
    featured: true,
    badge: 'known',
    parse: { fallbackRebarTon: 65500 },
  },
];

export function todayIso() {
  return new Date().toISOString().slice(0, 10);
}
